spring:
  application:
    name: demo-gateway
  r2dbc:
    name: test
    url: r2dbc:h2:mem://~/test

jwt:
  secret-key: temporary-secret-key-temporary-secret-key-temporary-secret-key-temporary-secret-key-temporary-secret-key-temporary-secret-key-temporary-secret-key-temporary-secret-key-temporary-secret-key

